### ISSUE TITLE
bandcamp downloader won't download

### ISSUE THREAD

**Issue by seanmbrosnan** [jaymoulin/bandcamp-down-chrome-ext#16]
I get a notification that tells me ''1% initializing...'' but nothing seems to happen, I don't even get a download error notification, all the songs say ''waiting''.
 I've tried restarting chrome, resetting router, uninstalling, reinstalling the program, but hasn't resolved the issue. Is anyone else having this problem?

**Comment by jaymoulin** [comment]
Might be related to #15. This will stay open until selling process is done.

**Comment by jaymoulin** [comment]
Extension has been sold to quotetab.com. You can contact them at support@quotetab.com.

You can still donate me to continue making great extensions :
[![Bitcoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/btc.png "Bitcoin donation")](https://m.freewallet.org/id/374ad82e/btc)
[![Litecoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ltc.png "Litecoin donation")](https://m.freewallet.org/id/374ad82e/ltc)

Also, for unknown reason, the new dev team reintegrated support to this github and my paypal donation button, so feel free to donate me :)

**Comment by jaymoulin** [comment]
The selling process of this extension turned extremely bad and the new acquirer refuses to pay what's due. The new acquirer said it will not fix the issue. As a result I will not publish sources anymore publicly and will probably start over again. 

Please consider making donation so we could make a great extension together.

[![Bitcoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/btc.png "Bitcoin donation")](https://m.freewallet.org/id/374ad82e/btc)
[![Litecoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ltc.png "Litecoin donation")](https://m.freewallet.org/id/374ad82e/ltc)

**Comment by Nao** [comment]
Are you aware that Bandcamp Downloader (which I understand you're no longer in control of, so I've disabled it) now seems to be malware?

To be specific: it injects itself into all web pages (which is already suspicious enough as it is...), and tries to contact 'netanalitics.space' which in turns adds a hex-encoded script which loads another script from 'labeyrietechnology.com', which in turns checks if this is a Google page and seamlessly adds extra ads at the top and bottom of the page. (It's very obvious-- because it takes time to load & decrypt everything and it loads at the end of the page anyway, the script only executes long after the page is done loading...)

Looks like Chrome removed the extension from its website, so there's that, but anyone who installed the extension back in the day (I know it was last year for me), and completely forgot about it, is now being targeted with that malware/adware attack.

**Comment by jaymoulin** [comment]
You can install KeepTune instead which is my original code without the malware thing. I have to insert a script into bandcamp pages to be able to catch javascript variables that gives numerous informations to make this extension possible
